image: node:latest

stages:
  - install
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - cache/Cypress
    - node_modules
    - build

install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline

bundle_app:
  stage: build
  script:
    - npm run build

e2etest:
  stage: test
  image: cypress/browsers:node18.12.0-chrome106-ff106
  only:
    - main
  script:
    - echo "Starting static server"
    - npx serve -s ./build -l 3000 &
    - echo "Waiting for server to start"
    - sleep 10 # Wait for the server to start
    - echo "Running Cypress tests"
    - npx cypress run --browser chrome